### ISSUE TITLE
Cannot create a production build

### ISSUE THREAD

**Issue by devfcr** [miltador/angular-amazon-login#13]
Hi,

when I try to create a production build with angular cli the compiler complains with this error message:

`ERROR in Error: Unexpected value 'AmazonLoginComponent in /Users/devfcr/Projects/testcloud/client/webclient/node_modules/angular-amazon-login/index.d.ts' declared by the module 'AppModule in /Users/devfcr/Projects/testcloud/client/webclient/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
    at Error (native)
    at syntaxError (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at /Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:15630:40
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:15612:54)
    at addNgModule (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24408:58)
    at /Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24419:14
    at Array.forEach (native)
    at _createNgModules (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:26)
    at analyzeNgModules (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24293:14)
    at analyzeAndValidateNgModules (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:24303:35)
    at AotCompiler.analyzeModulesAsync (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler/bundles/compiler.umd.js:23937:46)
    at CodeGenerator.codegen (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/Users/devfcr/Projects/testcloud/client/webclient/node_modules/@ngtools/webpack/src/plugin.js:386:44)`

You can reproduce this issue by using the 'ng build -prod' command.

I would appreciate if you could take a look at this issue.

**Comment by miltador** [comment]
Hi! I will look into it this weekend, bare with me!

**Comment by Antonyselt** [comment]
Is this issue already solve?

**Comment by jgrant95** [comment]
Ever find out the issue to this?? Thinking of trying to use this for an application. Would be very helpful.

Regards

**Comment by dillilabs** [comment]
we are hitting the same snag. Will appreciate if a fix can be delivered for this.

**Comment by devfcr** [comment]
Is there anything new on this?

**Comment by shreyash-sankey** [comment]
Any updates on this ? It is impacting prod release :(

**Comment by shreyash-sankey** [comment]
@miltador Anything?
